---
title       : Data Science Specialization Portfolio
subtitle    : A Johns Hopkins University Program
author      : Erik Cornelsen 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow   # 
mode        : selfcontained # {standalone, draft}
output: 
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    theme: spacelab
    toc: yes
    toc_depth: 4
---

#Introduction
The Data Science Specialization from Johns Hopkins University covers the concepts and tools used throughout the entire data science pipeline, from asking the right kinds of questions to making inferences and publishing results. The specialization consists of 9 courses and concludes with a Capstone project where I applied the skills I learned throughout the courses.


#Coursework Portfolio
This portfolio will give an description of the coursework and links to projects completed. You can also find find detailed descriptions of the coursework at the Coursera website [here](https://www.coursera.org/specialization/jhudatascience/).  


##Data Scientist's Toolbox
An intro/overview of the concepts, questions, data, and tools that data scientists work with. Specific tools covered included git, GitHub, markdown, R, RStudio, amd R markdown. 

**Project:** Open and use a [GitHub account](https://github.com/GitKlip)  
**Certificate:** [The Data Scientist's Toolbox](https://www.coursera.org/account/accomplishments/certificate/6VWPX89KX7)


##R Programming
Programming in R for effective data analysis, reading data into R, accessing R packages, writing R functions, debugging, profiling R code, organizing and commenting R code. 

**Project:** [File Manipulation](./02-RProgramming/rprog-p1-airpollution) - Create functions that read 332 .csv files from a directory, create a data set, and calculate some basic statistics on the data.    
**Project:** [Lexical Scoping](./02-RProgramming/rprog-p2-cachematrix/) - Create a funtion and use scoping rules in R to calculate the inverse of a matrix and cache the results.    
**Project:** [Rank Hospitals](./02-RProgramming/rprog-p3-hospital/) - Create 4 R functions to 1) Identify 30-day mortality rates for heart attack. 2) Rank hospitals by state. 3) Rank Hospitals by Outcome in a State. 4) Rank hospitals in all states.  
**Certificate:** [R Programming](https://www.coursera.org/account/accomplishments/certificate/V5CF574NG9)  


##Getting and Cleaning Data
Obtaining data from the web, APIs, databases and colleagues in various formats. Basics of data cleaning and creating "tidy" datasets to speed downstream data analysis tasks. Understanding the components of a 'complete' data set (raw data, processing instructions, codebooks, and processed data). 

**Project:** [Tidy Dataset](./03-GetAndCleanData/project/README.md) - Create a function that will produce a tidy dataset and create a Code Book that describes the the data and the steps taken.  
**Certificate:** [Getting and Cleaning Data](https://www.coursera.org/account/accomplishments/certificate/HF6AC5QBH3)  



##Exploratory Data Analysis
Essential exploratory techniques for summarizing and plotting data to inform and guide the development of more complex and formal statistical models. Practice with three R plotting systems: *Base Plotting System, Lattice Plotting System and ggplot2*.

**Project:** [Exploration of electric power consumption data](./04-ExploratoryDataAnalysis/ExData_Project1/README.md)  
**Project:** [Exploration of PM2.5 emissions Data](http://rpubs.com/ercorne/ExData_Project2) |  [source](./04-ExploratoryDataAnalysis/ExData_Project2/ExData-project2.Rmd)  
**Certificate:** [Exploratory Data Analysis](https://www.coursera.org/account/accomplishments/certificate/ZKD5QDTFRG)  


##Reproducible Research
Wrote analysis document using R markdown, integrated live R code into a literate statistical program, compiled R markdown documents using knitr, organize a data analysis so that it is reproducible and accessible to others, and publish the analysis using Rpubs.

**Project:** [Analysis of Personal Activity Monitoring](./05-ReproduceableResearch/RepData_Project1/PA1_template.Rmd)  
**Project:** [Report on Storm Impacts in the United States](http://rpubs.com/ercorne/severeweather) | [source](./05-ReproduceableResearch/RepData_Project2/PA2_template.Rmd)  
**Certificate:** [Reproducible Research](https://www.coursera.org/account/accomplishments/certificate/RPAZZM9DV2)  


##Statistical Inference
Statistical inference is the process of drawing conclusions about populations or scientific truths from representative data. Studied the fundamentals of statistical inference in a practical approach for getting things done. Topices covered include: probability, expected Values, variability, distributions, limits, confidence intervals, intervals, testing, pvalues, power, bootstrapping, and permutation tests.

**Project:** [Tooth Growth Analysis](./06-StatisticalInference/projects/Project_Analysis_ToothGrowth.pdf)  
**Project:** [Statistical Inference Simulation and Analysis](./06-StatisticalInference/projects/Project_Simulation_ExpAndCLT.pdf)  
**Certificate:** [Statistical Inference](https://www.coursera.org/account/accomplishments/certificate/JWBZ5SDP7U6Q)  


##Regression Models
Learned and applied linear regression models for prediction.  Topics learned: regression analysis; least squares; inference using regression models; multivariable regression; ANOVA and ANCOVA; Analysis of residuals and variability; model selection; using regression models for scatterplot smoothing

**Project:** [Motor Trend Analysis - Manual vs Automatic Transmission](./07-RegressionModels/projects/7-RegressionModels-Project.pdf) | [Source](./07-RegressionModels/projects/7-RegressionModels-Project.Rmd)  
**Certificate:** [Regression Models](https://www.coursera.org/account/accomplishments/certificate/MY6KRNLRVFNB)  


##Practical Machine Learning
Applied the basic components of building and applying prediction functions. Created training and tests sets while dealing with overfitting and error rates. Used various machine learning algorithms including regression, classification trees, Naive Bayes, and random forests through the complete process of building prediction functions including data collection, feature creation, algorithms, and evaluation.

**Project:** [Quality Classificationa of Human Exercises](./08-MachineLearning/projects/ML_Project.pdf) | [Source](./08-MachineLearning/projects/ML_Project.Rmd)  
**Certificate:** [Pratical Machine Learning](https://www.coursera.org/account/accomplishments/certificate/9DKPUF8BF4EU)  


##Developing Data Products
Learn how to communicate a statistical analysis output with a data product. The course covers shiny which is a web APP, R packages, rchart, Googlevis ,interactive graphics and slidify. The project is to create a data product to tell a story about the data to a mass audience.

A data product is the production output from a statistical analysis. Data products automate complex analysis tasks or use technology to expand the utility of a data informed model, algorithm or inference. This course covers the basics of creating data products using Shiny, R packages, and interactive graphics. The course will focus on the statistical fundamentals of creating a data product that can be used to tell a story about data to a mass audience.

**Project:** [Interactive Shiny WebApp](https://cornelsen.shinyapps.io/shinyCurrentHomePrice/) | [Source](./09-DataProducts/projects/shinyCurrentHomePrice/app.R) | [Presentation](http://rpubs.com/ercorne/shinyHomeHPI)  
**Certificate:** [Developing Data Products](https://www.coursera.org/account/accomplishments/certificate/A3K54UZCR6JE)  


##Capstone Project - Text Mining & NLP  (IN PROGRESS)
create a usable/public data product in collaboration with SwiftKey (developer of keyboard apps). 
* Analyze a large corpus of text documents to discover the data structure
* Clean text data and perform complex regressions
* Create visualizations and presentation to communicate your data analyses
* Build a predictive data model for analyzing large textual data sets
* Build a final data product 

**Project:** In Process
**Certificate:** In Process
